### ISSUE TITLE
In R2 rotated CommunityOS image, icons and touch areas do not align

### ISSUE THREAD

**Issue by tkocou** [WheresWaldo/CommunityOS#23]
After building an image for the R2 printer, I found that the displayed screen was inverted. The image was rebuilt using the rotate option in the config file.
After installing the new image into a SDcard and powering the R2 printer, the display was correct.
However, the touch areas per each icon are still inverted. Example, in the main screen, touching the **Status** icon pulls up the **System** screen instead of the true status screen. Once the **System** screen is displayed, I had to touch the opposite diagonal corner to return to the main screen. Touching the return icon accomplished nothing.

**Comment by WheresWaldo** [comment]
I got part of this working. Still need to test with actual R2, but it works with the 4.3" screen.
